NIFTY50_NAMES = {
    "ADANIENT.NS": "Adani Enterprises Ltd",
    "ADANIPORTS.NS": "Adani Ports & SEZ Ltd",
    "APOLLOHOSP.NS": "Apollo Hospitals Enterprise Ltd",
    "ASIANPAINT.NS": "Asian Paints Ltd",
    "AXISBANK.NS": "Axis Bank Ltd",
    "BAJAJ-AUTO.NS": "Bajaj Auto Ltd",
    "BAJAJFINSV.NS": "Bajaj Finserv Ltd",
    "BAJFINANCE.NS": "Bajaj Finance Ltd",
    "BHARTIARTL.NS": "Bharti Airtel Ltd",
    "BPCL.NS": "Bharat Petroleum Corp Ltd",
    "BRITANNIA.NS": "Britannia Industries Ltd",
    "CIPLA.NS": "Cipla Ltd",
    "COALINDIA.NS": "Coal India Ltd",
    "DIVISLAB.NS": "Divi's Laboratories Ltd",
    "DRREDDY.NS": "Dr. Reddy's Laboratories Ltd",
    "EICHERMOT.NS": "Eicher Motors Ltd",
    "GRASIM.NS": "Grasim Industries Ltd",
    "HCLTECH.NS": "HCL Technologies Ltd",
    "HDFCBANK.NS": "HDFC Bank Ltd",
    "HDFCLIFE.NS": "HDFC Life Insurance Co Ltd",
    "HEROMOTOCO.NS": "Hero MotoCorp Ltd",
    "HINDALCO.NS": "Hindalco Industries Ltd",
    "HINDUNILVR.NS": "Hindustan Unilever Ltd",
    "ICICIBANK.NS": "ICICI Bank Ltd",
    "INDUSINDBK.NS": "IndusInd Bank Ltd",
    "INFY.NS": "Infosys Ltd",
    "ITC.NS": "ITC Ltd",
    "JSWSTEEL.NS": "JSW Steel Ltd",
    "KOTAKBANK.NS": "Kotak Mahindra Bank Ltd",
    "LT.NS": "Larsen & Toubro Ltd",
    "LTIM.NS": "LTIMindtree Ltd",
    "M&M.NS": "Mahindra & Mahindra Ltd",
    "MARUTI.NS": "Maruti Suzuki India Ltd",
    "NESTLEIND.NS": "Nestle India Ltd",
    "NTPC.NS": "NTPC Ltd",
    "ONGC.NS": "Oil & Natural Gas Corp Ltd",
    "POWERGRID.NS": "Power Grid Corp of India Ltd",
    "RELIANCE.NS": "Reliance Industries Ltd",
    "SBILIFE.NS": "SBI Life Insurance Co Ltd",
    "SBIN.NS": "State Bank of India",
    "SUNPHARMA.NS": "Sun Pharmaceutical Industries Ltd",
    "TATACONSUM.NS": "Tata Consumer Products Ltd",
    "TATAMOTORS.NS": "Tata Motors Ltd",
    "TATASTEEL.NS": "Tata Steel Ltd",
    "TCS.NS": "Tata Consultancy Services Ltd",
    "TECHM.NS": "Tech Mahindra Ltd",
    "TITAN.NS": "Titan Company Ltd",
    "ULTRACEMCO.NS": "UltraTech Cement Ltd",
    "UPL.NS": "UPL Ltd",
    "WIPRO.NS": "Wipro Ltd"
}
